### ISSUE TITLE
[firefox] comment box is tiny and not resizable

### ISSUE THREAD

**Issue by ankush** [frappe/gameplan#100]
Comment box is not resizable and very tiny

![image](https://user-images.githubusercontent.com/9079960/192255448-7537d3dc-74d8-4421-8a90-76c6d1032304.png)

new post is okay but looks kinda weird with the outline.
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/9079960/192255742-94221acd-e9da-4f6a-beba-32c3eab7cc0d.png">

Probably a bug in tiptap but still we have to support firefox.

**Comment by netchampfaris** [comment]
Our first Firefox-specific CSS is here 😄 

https://github.com/frappe/frappe-ui/commit/171e738b3b13a2325385da408b2e3d538f5e7e3d

**Comment by netchampfaris** [comment]
@ankush Btw, the comment box size is the same in all browsers, just that Firefox shows an outline on focus (which is hidden in other browsers).
