### ISSUE TITLE
[Feature] Mark Project as Completed with Option to Archive 

### ISSUE THREAD

**Issue by chechani** [frappe/gameplan#102]
It seems right now all running and completed projects are visible , Marking Project as Completed and showing not completed projects by default with option to jump to see all projects. Tabs can be given for completed/archiced projects and Open Projects can be given here ( below screen) as given for Open and Closed Tasks

![image](https://user-images.githubusercontent.com/6291292/192433948-0cd233d7-0878-4a20-951b-9b9aab82be8d.png)

**Comment by netchampfaris** [comment]
https://github.com/frappe/gameplan/commit/88dea73f60dc594488ecb807b3aa682d00640e65
