### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/gameplan#11]
<img width="1028" alt="Screenshot 2022-08-08 at 12 06 24 PM" src="https://user-images.githubusercontent.com/34810212/183355586-52cfb494-9ace-47b0-95a1-eadb4b4850f5.png">

Show name of the post instead?
<img width="854" alt="Screenshot 2022-08-08 at 12 08 18 PM" src="https://user-images.githubusercontent.com/34810212/183355594-c282db36-fee1-471e-96a8-71cb2855eb7b.png">

Padding (intentional?):
<img width="1197" alt="Screenshot 2022-08-08 at 12 10 05 PM" src="https://user-images.githubusercontent.com/34810212/183355611-e9d03ec9-b258-4657-9458-007e879209b5.png">

**Comment by netchampfaris** [comment]
All of these issues are fixed via multiple fixes.
