### ISSUE TITLE
Feature request: show Task updates, assigned tasks in home.

### ISSUE THREAD

**Issue by iMoshi** [frappe/gameplan#110]
Currently "home" only shows Discussions, which is fine but this isn't sufficient to catch up with all Task updates. 

I'm requesting you guys to create a new page that shows Tasks updates. It should show the dropdown filter (like Filter by Team in Home) and from there you could choose between "My tasks", "Created by me", "All tasks" and most importantly it should show the comments in a "Load comments" (button) fashion 😁

I think this can help supervisors keep a tab on all tasks that are happening, rather than going into a Team, then a Project, and then a Tasks. 

Please keep this in mind, thanks guys.

**Comment by rmehta** [comment]
+1 - This is a basic requirement for task management. Need to keep track of "My tasks" and "Tasks assigned to me" globally as well as per project.

**Comment by rmehta** [comment]
Starting to use tasks actively now. Missing this feature.

**Comment by netchampfaris** [comment]
This is now implemented via https://github.com/frappe/gameplan/commit/bde27d97947626f7c98c49e8a121b2641e40d060

**Comment by iMoshi** [comment]
Love it! 

However, my comments to the task are not inserting, giving the following error:

`Uncaught (in promise) Error: /api/method/frappe.client.insert
    at Object.transformResponse (frappeRequest.js:71:17)
    at async Proxy.i (resources.js:103:18)`

Just FYI :)
