### ISSUE TITLE
`Cmd`+`S` for saving Project Description

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/gameplan#121]
I assume `Cmd`+`S` will work here every single time:

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/34810212/195224975-254ec511-baf2-4947-a21c-0ecb4c2fd81f.png">

**Comment by ankush** [comment]
It should be cmd+enter? Common convention in text editors in many places (even comments on GP itself)

**Comment by netchampfaris** [comment]
+1 @ankush

@NagariaHussain Haven't seen `Cmd + S` as a keyboard shortcut in modern web apps.
