### ISSUE TITLE
/teams to /gameplan ?

### ISSUE THREAD

**Issue by rmehta** [frappe/gameplan#122]

**Comment by netchampfaris** [comment]
I was thinking of a single letter, g.


- https://company.gameplan.so/g/marketing/overview
- https://company.gameplan.so/g/marketing/projects/2/discussions

**Comment by rmehta** [comment]
`g` is cool! - `t` might always work as semantically its points to the team?

**Comment by netchampfaris** [comment]
Ended up doing `/g` because there are other non-team routes as well

- https://company.gameplan.so/g/home
- https://company.gameplan.so/g/search
