### ISSUE TITLE
Link to go to team page (parent) from project page is missing

### ISSUE THREAD

**Issue by rmehta** [frappe/gameplan#123]
<img width="783" alt="Screenshot 2022-10-12 at 2 25 42 PM" src="https://user-images.githubusercontent.com/140076/195298194-ab6170f6-9f7c-4d00-95eb-10894e3bebb0.png">

**Comment by netchampfaris** [comment]
Fixed via https://github.com/frappe/gameplan/commit/a1895af46277856e95cc1f3e12503ab74abf952c
