### ISSUE TITLE
/people: Change default to last updated

### ISSUE THREAD

**Issue by rmehta** [frappe/gameplan#127]
<img width="555" alt="Screenshot 2022-10-17 at 11 49 57 AM" src="https://user-images.githubusercontent.com/140076/196103017-067bfa79-b2ea-44db-969b-ba1580ace20e.png">

**Comment by netchampfaris** [comment]
https://github.com/frappe/gameplan/commit/c79ecfcb13f57a72f802b44877e9595b9b6afa7b
