### ISSUE TITLE
Signin page issue 

### ISSUE THREAD

**Issue by EnSeal** [frappe/gameplan#132]
I was able to install the app using the documentation, but I am not able to login using the username setup with frappe. 

I am getting the error. Where do i set the username to use for the app ?

![image](https://user-images.githubusercontent.com/18033246/196649524-fb2d410b-ef49-4d48-a944-edca8ce6af56.png)

**Comment by jango-blockchained** [comment]
Same here

**Comment by olamide2** [comment]
Same here

**Comment by jango-blockchained** [comment]
To be complete...

User: Administrator
Password: admin
