### ISSUE TITLE
Subscribe/unsubscibe to project

### ISSUE THREAD

**Issue by ankush** [frappe/gameplan#154]
I dont want to see everything :grimacing:

**Comment by uhrjun** [comment]
If this gets implemented, maybe consider adding a toggle to default a new project to unsubscribe for all users. So they have to explicitly subscribe to it. The use case I have in mind being, if a dev wanted to push a weekly dev log of what they got up to (I really want to :p). Or, something that only pertains to the immediate dept/team and isn't high priority enough to populate the main homepage with.

**Comment by ankush** [comment]
https://github.com/frappe/gameplan/commit/b76278e400ee245703fc375f0e60cf6207f59084

This is it
