### ISSUE TITLE
Please let me change/re-arrange my cover photo

### ISSUE THREAD

**Issue by ssiyad** [frappe/gameplan#158]
`Change Image`/`Reposition` buttons disappears on hover
> https://user-images.githubusercontent.com/28098330/200341513-dd235a43-3d8e-46e7-a437-8da5e809627c.mov

**Comment by netchampfaris** [comment]
https://github.com/frappe/gameplan/commit/4c8ce6c516c22a38e62c9e40d5c5d191306e60f2
