### ISSUE TITLE
Installing gameplan to site gives ImportError: Module import failed for Team Discussion

### ISSUE THREAD

**Issue by fadilsid** [frappe/gameplan#162]
I'm trying to install game plan to my site and it gives following error:

ImportError: Module import failed for Team Discussion, the DocType you're trying to open might be deleted.<br> Error: No module named 'redis.commands'

![Screenshot from 2022-11-18 17-39-10](https://user-images.githubusercontent.com/73826691/202702515-35f84de7-c6fa-484f-92b6-3c1585873268.png)

**Comment by ankush** [comment]
Gameplan only works on develop branch as of now

https://github.com/frappe/gameplan/issues/137
