### ISSUE TITLE
perf: Do image processing in background jobs

### ISSUE THREAD

**Issue by ankush** [frappe/gameplan#175]
loading the model and processing it keeps it in memory

![image](https://user-images.githubusercontent.com/9079960/210266474-e089bd21-c883-4e94-a3d4-0e01f403b4db.png)

- Idle usage is ~80-100MB. 
- Just going to people pages bumps memory usage to 200MB. probably from library imports?
- Removing BG of one image bumps memory usage to 400MB+

Background jobs don't suffer from this as the process is forked and dies after job is completed.

**Comment by netchampfaris** [comment]
Bg removal is done at server side, there are no client libraries. Will try with background job.

**Comment by ankush** [comment]
@netchampfaris but it's done in web request right? So gunicorn worker loads rembg and it's models in memory and doesn't unload it ever I guess.

**Comment by ankush** [comment]
Just importing it is 80MB hit :grimacing: 

![image](https://github.com/frappe/gameplan/assets/9079960/7c49d942-b2c1-49f8-a6cd-d3e6029b61f7)




![image](https://github.com/frappe/gameplan/assets/9079960/4ae89de1-3ad2-4d3f-978a-a059dbfe8e32)

**Comment by ankush** [comment]
https://github.com/frappe/gameplan/commit/8cfe45ecb2f7e8737033a6c624c46c18cf7d97db

This reduces the effect of it (will only load in memory if function is actually called. But it still needs to be moved to the background.

**Comment by netchampfaris** [comment]
https://github.com/frappe/gameplan/commit/bdbff9b625b8cb499a6536cd6da73156be0e2965
