### ISSUE TITLE
When creating a new topic, sometimes content from last topic shows up

### ISSUE THREAD

**Issue by rmehta** [frappe/gameplan#177]
![dirty](https://user-images.githubusercontent.com/140076/210485018-63ec3b3a-99f6-4580-b19a-b2a712bafb48.gif)

**Comment by netchampfaris** [comment]
When composing a new post, the data is stored locally in the browser so that the user doesn't lose their work on refresh. It gets cleared when the user clicks on Discard or Publish.

Is there any other flow which makes this behaviour buggy?

**Comment by rmehta** [comment]
yep, sometimes the cache does not clear when I publish - will try and find out if I can replicate it.

**Comment by netchampfaris** [comment]
Closing until replicable
