### ISSUE TITLE
Default login/password

### ISSUE THREAD

**Issue by yatish27** [frappe/gameplan#192]
When starting the app via docker-compose, it shows the login page.
What is the default username and password?

**Comment by netchampfaris** [comment]
I have fixed this via https://github.com/frappe/gameplan/commit/7cecd73b8f64774524918353ce5397e2ef74fc1f

If you can access the docker console, you can run this command to add a user:
https://github.com/frappe/gameplan/blob/7cecd73b8f64774524918353ce5397e2ef74fc1f/docker/init.sh#L37
