### ISSUE TITLE
frappe 14.28.2 requires Click~=7.1.2, but you have click 8.1.3

### ISSUE THREAD

**Issue by iMoshi** [frappe/gameplan#196]
I have Gameplan (which I think is awesome) installed on my Frappe instance, and upon `bench update`-ing I've encountered Gameplan requires click 7.1.2, but Frappe used rembg which requires click 8.1.3. 

Can you guys talk this out in the team 😅 and resolve which to use 😉 thank you guys!

**Comment by ankush** [comment]
https://github.com/frappe/gameplan/issues/137

**Comment by iMoshi** [comment]
This has nothing to do with Redisearch, and I do have a test bench that's running develop branch of Frappe :) 

Well, hope you guys will solve this in the near future as Gameplan is a beautiful app!
