### ISSUE TITLE
Frappe Cloud v13 - v14 availability

### ISSUE THREAD

**Issue by bkopy** [frappe/gameplan#212]
Hi there!

I wanted to install Gameplan on a Frappe Cloud, the thing is that I couldn't.

- I see this bug: #137 
- There is no possibility to install with v13 because app is not available.

Please make available the Frappe v13 + Gameplan combo for benches or fix the redis problem, because this way there is no possible "one click" install only the local machine or private cloud.

Thank in advance.

**Comment by ankush** [comment]
Please dont create duplicate issues

**Comment by ankush** [comment]
Also, private cloud is not required. You can set up gameplan on the cheapest 10$ site too. Just make sure it's on nightly bench.
