### ISSUE TITLE
Not able to see teams, projects in the default views

### ISSUE THREAD

**Issue by hari-madhavan** [frappe/gameplan#218]
When teams are created they remain persistent and are accessible through their url. However they are not accessible in the teams ( on homepage )

Similarly already created  projects under teams are not visible but when the specific url for the poject is given it is shown ( two screenshots attached )

![Screenshot from 2023-05-24 13-45-36](https://github.com/frappe/gameplan/assets/51024798/f8bed5fe-ed17-467a-b5a8-fda9134f6e5c)
![Screenshot from 2023-05-24 13-46-01](https://github.com/frappe/gameplan/assets/51024798/a189baf8-7dcc-47aa-8cf2-504649048917)

Similar error happens for discussions as well  - screenshot attached ( the discussions show a count of 2 but nothing is listed )

![Screenshot from 2023-05-24 13-46-07](https://github.com/frappe/gameplan/assets/51024798/8f48a31b-4773-4ba1-8e59-bf1edefd04f6)

**Comment by netchampfaris** [comment]
**Gameplan Admin** or **Gameplan Member** must be applied to the user for the Gameplan UI to work properly.

**Comment by netchampfaris** [comment]
> Didn't look into the code, but could be that guests have restricted views ?

You are right, users with a Guest role have restricted views.

**Comment by netchampfaris** [comment]
This is now fixed, closing.
