### ISSUE TITLE
SocketIO namespace needs `frappe.local.site`

### ISSUE THREAD

**Issue by ankush** [frappe/gameplan#240]
https://github.com/frappe/gameplan/blob/0e56e421c8d61e5e63c1556624fb6bac9bd11d3c/frontend/src/socket.js#L8

`host` won't be same as `site` in case of multiple domains

**Comment by netchampfaris** [comment]
https://github.com/frappe/gameplan/commit/4ae45c8ac12218a92025bb6fe9a5e9f922958c8e
