### ISSUE TITLE
Gameplan Interface is Different, My Profile when click nothing Happened / No Delete / Rename on team section 

### ISSUE THREAD

**Issue by yhennie** [frappe/gameplan#247]
Good Day, I try to installed gameplan on my windows machine my frappe version is 15 develop but when i click on my profile nothibg happen, also i cant edit the name of the teams i made or delete it. 

clicking on profile nothing happend 
![Screenshot 2023-09-09 154357](https://github.com/frappe/gameplan/assets/61680603/729426e2-d049-4fc9-9469-d8b77bb73d08)

no delete / rename option  
![Screenshot 2023-09-09 154735](https://github.com/frappe/gameplan/assets/61680603/601dfe38-4434-4535-ac56-9a4dff18042d)

**Comment by netchampfaris** [comment]
@yhennie Please login as a normal user not Administrator.

@the3dfox Please open a new issue, if it still persists.
