### ISSUE TITLE
Lost page contents

### ISSUE THREAD

**Issue by NehaSan16** [frappe/gameplan#249]
I updated a page with a lot of text and images

Scrolled to a few discussions 

When I came back to the page, the contents were reverted to the older saved version (15 mins ago) and I lost all updates :( 
https://gameplan.frappe.cloud/g/engineering/projects/136/pages/68/plg-teardown-zoho-inventory

@netchampfaris

**Comment by netchampfaris** [comment]
Sorry to hear that you lost content 😞 
I have made some changes to remove unnecessary realtime update and also added a Save button.
https://github.com/frappe/gameplan/commit/d2a8ab6022365818eb95bc0145c7a29658d1c33e
