### ISSUE TITLE
Unable to see my pages under "my pages" 

### ISSUE THREAD

**Issue by NehaSan16** [frappe/gameplan#256]
<img width="1410" alt="Screenshot 2023-11-21 at 1 02 45 PM" src="https://github.com/frappe/gameplan/assets/139349833/979e29f7-7301-479f-aa19-8518e66321fe">

Have ~4 to 5 pages published but I am unable to see them under my-pages and some times it is difficult to remember which project > channel I have published my pages under.

**Comment by netchampfaris** [comment]
This should be fixed now
