### ISSUE TITLE
Created my site but don't see an option to invite members

### ISSUE THREAD

**Issue by NehaSan16** [frappe/gameplan#277]
<img width="1414" alt="Screenshot 2024-03-17 at 6 08 46 PM" src="https://github.com/frappe/gameplan/assets/139349833/30e6fd73-2275-4d10-82a7-fa9670a61ea2">

**Comment by NehaSan16** [comment]
Adding a new member is challenging. No clue how to set up a default account. 


<img width="1003" alt="Screenshot 2024-03-17 at 6 21 47 PM" src="https://github.com/frappe/gameplan/assets/139349833/0f4eeab4-e2b9-40ff-b217-43d4e5e4c194">

**Comment by huembw** [comment]
I think this issue was fixed recently. You can check again

**Comment by netchampfaris** [comment]
1. To invite people, you should be logged in as a System User and not Administrator. 
2. Although email setup is not straightforward, it is not a concern of Gameplan.

Closing.
