### ISSUE TITLE
Creates 2 duplicate projects when I create a new project using Add Project button 

### ISSUE THREAD

**Issue by thegratitudeapp** [frappe/gameplan#282]
I'm using the main branch of gameplan on frappe cloud. I'm noticing that when I create a team or new projects inside a team, it creates 2 duplicate new teams/projects. It's not reproducible every time. However, in the last few times I have tried doing so, 2/5 times I have seen this happening.

**Comment by huembw** [comment]
Same issue :<

**Comment by huembw** [comment]
It's fixed 👌

**Comment by netchampfaris** [comment]
Fixed in 6e5268ef619ce205e3966cc7188eea6c341524da
