### ISSUE TITLE
Can't assign task to user

### ISSUE THREAD

**Issue by aedudon** [frappe/gameplan#292]
when i try to assign a task to user. List show the user, i choose username. But its show nothing change
![image](https://github.com/frappe/gameplan/assets/109790101/c2f3049b-f925-4fad-ac2d-35c821551bba)
![image](https://github.com/frappe/gameplan/assets/109790101/ac32435f-61a3-4fce-a154-40f4477b31de)

**Comment by blaggacao** [comment]
I can confirm on (at least): 89315d218ba91b8ccbc477930128e57595c8c07a

**Comment by blaggacao** [comment]
@netchampfaris This is _really_ the most annoying among all the "polishing" issues open. Could you maybe try to fix this with some priority so that Gameplan becomes "mostly" usable with the caveats of the other issues reported?

**Comment by blaggacao** [comment]
It appears this requires websocket via ws and does not work (well/at all) with long polling.
