### ISSUE TITLE
minor ux: Highlight selected dates

### ISSUE THREAD

**Issue by abhishekbalam** [frappe/gameplan#30]
Maybe like in Assignment, date after selection can be in black as opposed to the grey.

<img width="213" alt="image" src="https://user-images.githubusercontent.com/15175501/184092616-d3440079-4a00-44ea-aaf8-40063334250c.png">

**Comment by netchampfaris** [comment]
This is now fixed via https://github.com/frappe/gameplan/commit/838f2481c7baa8f1200739269725f8a120596f58
