### ISSUE TITLE
Not able to assign user in task

### ISSUE THREAD

**Issue by akhtarmohsin** [frappe/gameplan#320]
In Project & Task, the user is unable to update the assignee in the task.

![image](https://github.com/user-attachments/assets/09dbfece-620e-4f83-9c6e-bea6a43f23a1)

![Screenshot 2024-10-07 at 11 33 11 AM](https://github.com/user-attachments/assets/c0811d37-6079-4afd-8fd0-3288236db24b)

**Comment by midhat2020** [comment]
@akhtarmohsin Any Updates?

**Comment by Niteshs19** [comment]
Same issue
