### ISSUE TITLE
Cannot delete Page despite being GP Admin

### ISSUE THREAD

**Issue by kittiu** [frappe/gameplan#334]
Despite being GP Admin, deletion on frontend is not working.
![Screenshot_20241021_091801_Chrome](https://github.com/user-attachments/assets/87b5fe2a-e90f-481d-bbcc-1a5b2f463896)

**Comment by kittiu** [comment]
Onclick error,

![image](https://github.com/user-attachments/assets/63bcea2d-adc2-4ffe-b1b5-4995aaff20a1)

**Comment by netchampfaris** [comment]
Fixed in latest
