### ISSUE TITLE
Minor issue in showing posted at time

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/gameplan#58]
<img width="1027" alt="Screenshot 2022-08-23 at 7 11 21 AM" src="https://user-images.githubusercontent.com/34810212/186049979-84540d89-10bc-4280-bf43-b82736f3bd09.png">

Shows "in a few seconds" just after I post the comment (should show "now" maybe?)

**Comment by netchampfaris** [comment]
<img width="440" alt="image" src="https://github.com/frappe/gameplan/assets/9355208/6b0d1c6e-14a1-4db5-b03e-d9de2d45b7be">

Fixed
