### ISSUE TITLE
feature request (Tasks): Closed state in Tasks along with Completed 

### ISSUE THREAD

**Issue by abhishekbalam** [frappe/gameplan#67]
When a task is created you can either:
1. Mark it as Complete
2. Delete it

But sometimes tasks change and they have to be closed when not completed.

In the counters per project there are the following cards:
1. Completed
2. Overdue
3. Pending
4. Total

When a task is marked as closed, it can be marked like right now in list view and not increment the counter in "Completed Tasks" card as opposed to now when we are forced to mark it as complete. "Total Tasks" card value remains unchanged.

**Comment by netchampfaris** [comment]
Tasks feature is now refactored to have these statuses: Backlog, Todo, In Progress, Done, and Canceled.
