### ISSUE TITLE
Email Notification for mentions

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/gameplan#91]
.

**Comment by NagariaHussain** [comment]
> Opinionated view: gameplan is async communication tool for teams, so it shouldn't have annoying notifications that get clubbed with the rest of the emails.
> 
> 
> 
> This can be provided as an option though, hopefully disabled by default. 
> 
> 
> 
> 
> 
> 

We can do something similar to what [twist](https://twist.com) does. So, not a immediate notification, but some kind of reminder of pending unread notifications.

**Comment by netchampfaris** [comment]
Duplicate of https://github.com/frappe/gameplan/issues/115
