### ISSUE TITLE
Team page refresh issue

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/gameplan#96]
When I create a new team then I can not show that new created team. I have to refresh the url then after I can see the new team.

**Comment by netchampfaris** [comment]
This should be fixed via https://github.com/frappe/gameplan/commit/ccc553cada2aed77a4760aafac0c099fd3f0d03f. Can you confirm?

**Comment by netchampfaris** [comment]
Closing

**Comment by mohsinalimat** [comment]
> This should be fixed via [ccc553c](https://github.com/frappe/gameplan/commit/ccc553cada2aed77a4760aafac0c099fd3f0d03f). Can you confirm?

Issue solve.
