### ISSUE TITLE
Public/Private Teams and Projects

### ISSUE THREAD

**Issue by netchampfaris** [frappe/gameplan#97]
When you create a team, it should have an option to set it's visibility to Public or Private. In a Private team, only members added to the team will see it on the sidebar and can get access to the Projects.

Similarly, there should be Projects of type Public or Private. If a Project is private, an "Add Member" button will show up, using which you should be able to give access to the Project to specific people.

Tasks:
- [ ] Private Team
- [x] Private Project
- [x] Invite a Guest user to a specific project

**Comment by iMoshi** [comment]
This needs to be bumped 😅 

I initially thought Inviting members to the project allowed them access, otherwise the project was hidden but I've realized non-members can actually Invite even themselves to the project :)

**Comment by netchampfaris** [comment]
Private Projects is implemented via https://github.com/frappe/gameplan/pull/112

**Comment by iMoshi** [comment]
> Private Projects is implemented via #112

Thank you Netchamp Faris! Though I feel like this should be extended to "Teams" as well 😅 It's just funny how there's a "For Directors only" team with no visible project inside them :)

**Comment by netchampfaris** [comment]
We'll get there, one feature at a time.

**Comment by netchampfaris** [comment]
Guest access to a project implemented via #166

**Comment by netchampfaris** [comment]
Private Team implemented via https://github.com/frappe/gameplan/pull/191
